// <auto-generated />
using System;
using ApiAeropuerto.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiAeropuerto.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiAeropuerto.Models.Reservas", b =>
                {
                    b.Property<long>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aerolinea")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("AeropuertoLlegada")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("AeropuertoOrigen")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("DocumentoPasajero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioLlegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombresPasajero")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("NumeroVuelo")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(18,0)");

                    b.Property<byte>("TipoPasajero")
                        .HasColumnType("tinyint");

                    b.HasKey("IdReserva");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            IdReserva = 1L,
                            Aerolinea = "AVIANCA",
                            AeropuertoLlegada = "ERNESTO CORTIZOS",
                            AeropuertoOrigen = "EL DORADO",
                            DocumentoPasajero = "85442315",
                            FechaReserva = new DateTime(2022, 1, 1, 10, 12, 45, 0, DateTimeKind.Unspecified),
                            HorarioLlegada = new DateTime(2022, 1, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            HorarioSalida = new DateTime(2022, 1, 1, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            NombresPasajero = "PEDRO PEREZ",
                            NumeroVuelo = 123,
                            Precio = 300000m,
                            TipoPasajero = (byte)1
                        },
                        new
                        {
                            IdReserva = 2L,
                            Aerolinea = "AVIANCA",
                            AeropuertoLlegada = "ERNESTO CORTIZOS",
                            AeropuertoOrigen = "EL DORADO",
                            DocumentoPasajero = "1052362478",
                            FechaReserva = new DateTime(2022, 1, 8, 10, 12, 45, 0, DateTimeKind.Unspecified),
                            HorarioLlegada = new DateTime(2022, 1, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            HorarioSalida = new DateTime(2022, 1, 1, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            NombresPasajero = "CARLOS MARTINEZ",
                            NumeroVuelo = 123,
                            Precio = 200000m,
                            TipoPasajero = (byte)2
                        },
                        new
                        {
                            IdReserva = 3L,
                            Aerolinea = "AVIANCA",
                            AeropuertoLlegada = "ERNESTO CORTIZOS",
                            AeropuertoOrigen = "EL DORADO",
                            DocumentoPasajero = "23105478",
                            FechaReserva = new DateTime(2022, 1, 11, 10, 12, 45, 0, DateTimeKind.Unspecified),
                            HorarioLlegada = new DateTime(2022, 1, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            HorarioSalida = new DateTime(2022, 1, 1, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            NombresPasajero = "CAROLINA SUAREZ",
                            NumeroVuelo = 123,
                            Precio = 300000m,
                            TipoPasajero = (byte)1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
